// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NbaEcommerce.Models;

namespace NbaEcommerce.Migrations.SqlServerMigration
{
    [DbContext(typeof(NbaStoreContext))]
    partial class NbaStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NbaEcommerce.Models.Categoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Attivo");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Dispositivo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<string>("Descrizione")
                        .IsRequired();

                    b.Property<Guid>("IdMarchio");

                    b.HasKey("Id");

                    b.HasIndex("IdMarchio");

                    b.ToTable("Dispositivo");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Immagine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<byte[]>("Data")
                        .IsRequired();

                    b.Property<Guid>("IdProdotto");

                    b.Property<string>("ImageInfo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.HasIndex("IdProdotto");

                    b.ToTable("Immagine");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Marchio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Attivo");

                    b.Property<string>("Descrizione")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .IsUnicode(false);

                    b.HasKey("Id");

                    b.ToTable("Marchio");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Prodotto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasDefaultValueSql("(newid())");

                    b.Property<bool>("Attivo");

                    b.Property<string>("Descrizione");

                    b.Property<Guid>("IdCategoria");

                    b.Property<Guid>("IdDispositivo");

                    b.Property<Guid>("IdMarchio");

                    b.Property<double>("PrezzoAcquisto");

                    b.Property<double>("PrezzoVendita");

                    b.Property<int>("Quantità");

                    b.Property<string>("Titolo");

                    b.HasKey("Id");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdDispositivo");

                    b.HasIndex("IdMarchio");

                    b.ToTable("Prodotto");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Dispositivo", b =>
                {
                    b.HasOne("NbaEcommerce.Models.Marchio", "IdMarchioNavigation")
                        .WithMany("Dispositivo")
                        .HasForeignKey("IdMarchio")
                        .HasConstraintName("FK_Dispositivo_Marchio");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Immagine", b =>
                {
                    b.HasOne("NbaEcommerce.Models.Prodotto", "IdProdottoNavigation")
                        .WithMany("Immagine")
                        .HasForeignKey("IdProdotto")
                        .HasConstraintName("FK_Immagine_Prodotto");
                });

            modelBuilder.Entity("NbaEcommerce.Models.Prodotto", b =>
                {
                    b.HasOne("NbaEcommerce.Models.Categoria", "IdCategoriaNavigation")
                        .WithMany("Prodotto")
                        .HasForeignKey("IdCategoria")
                        .HasConstraintName("FK_Prodotto_Categoria1");

                    b.HasOne("NbaEcommerce.Models.Dispositivo", "IdDispositivoNavigation")
                        .WithMany("Prodotto")
                        .HasForeignKey("IdDispositivo")
                        .HasConstraintName("FK_Prodotto_Dispositivo");

                    b.HasOne("NbaEcommerce.Models.Marchio", "IdMarchioNavigation")
                        .WithMany("Prodotto")
                        .HasForeignKey("IdMarchio")
                        .HasConstraintName("FK_Prodotto_Marchio1");
                });
#pragma warning restore 612, 618
        }
    }
}
